# Generated by Django 4.1.6 on 2023-02-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createnews',
            fields=[
                ('NewsId', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=150)),
                ('NewsDetails', models.TextField()),
                ('Coverimage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
